# Configuration file for DiM-A algorithm. See Algorithm 2 in https://arxiv.org/abs/2404.06025
---
encoding_timesteps: 250
sampling_timesteps: 100
scheduler_kwargs:
  n_train_steps: 1000
  solver_order: 1
  prediction_type: epsilon
  algorithm_type: dpmsolver
encoding_solver: diffae
